spring.application.name=backend


# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/reservex?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true     
spring.datasource.username=root
spring.datasource.password=20031217

 MySQL (Aiven)
spring.datasource.url=jdbc:mysql://reservex-lochithya12-14c4.b.aivencloud.com:26989/defaultdb?sslMode=REQUIRED&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password= AVNS_BLZPtQ1ZigImkB4OFMR

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://reservex-lochithya12-14c4.b.aivencloud.com:26989/defaultdb?sslMode=REQUIRED&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&verifyServerCertificate=false&allowPublicKeyRetrieval=true

#spring.datasource.url=jdbc:mysql://localhost:3306/reservex?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
jwt.secret=ReserveXColomboBookFairSecretKeyForJWTTokenGeneration2024
jwt.expiration-ms=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:pabodha726@gmail.com}
spring.mail.password=${MAIL_PASSWORD:tstksyjsepptqjoz}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.mail=DEBUG


